export const batonsList = {
  draft: {
    title: "Draft Batons",
    borderColor: "#5E94D4",
    bgColor: "#fff",
    status: "draft",
    id: 1,
  },
  pending: {
    title: "Pending Batons",
    borderColor: "#5f6b72",
    bgColor: "#fff",
    status: "pending",
    id: 2,
  },
  passed: {
    title: "Passed Batons",
    borderColor: "#EFB000",
    bgColor: "#FDF7E6",
    status: "passed",
    id: 3,
  },
  received: {
    title: "Received Batons",
    borderColor: "#8e2eb9",
    bgColor: "#F7EFFD",
    status: "received",
    id: 4,
  },
  accepted: {
    title: "Accepted Batons",
    borderColor: "#409000",
    bgColor: "#F4FDF2",
    status: "accepted",
    id: 5,
  },
  complete: {
    title: "Complete Batons",
    borderColor: "#196DB2",
    bgColor: "#F2F8FB",
    status: "complete",
    id: 6,
  },
  declined: {
    title: "Declined Batons",
    borderColor: "#EA4400",
    bgColor: "#FDEEE7",
    status: "declined",
    id: 7,
  },
};
